server:
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/kivabidb
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    hikari:
      pool-name: SpringBootBoilerplateHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jta:
    enabled: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.teten.kivabi.service.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: www.teten-tech.com
  expirationMinute: 10

swagger:
  contact-name: Teten Nugraha
  contact-mail: teten.dev@gmail.com
  contact-url: https://teten.com
  app-name: Spring Boot Boilerplate Project
  app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot(3.5.7), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API)"
  app-version: 3.5.7
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
